### ISSUE TITLE
Add support for new version of scikit-learn 

### ISSUE THREAD

**Issue by weixuanfu** [lacava/DistanceClassifier#1]
Please replace `from sklearn.cross_validation import train_test_split` to `from sklearn.model_selection import train_test_split` for new version scikit-learn, because the old one will be removed in version 0.20 of scikit-learn.  for the latest 0.18 version of scikit-learn a warning message will also show out when using this codes.

**Comment by lacava** [comment]
fixed by commit fb6f238. thanks.
